### PR TITLE
Add support for incremental OTAs

### PR DESCRIPTION
**Pull request by chenxiaolong**
Generating the incremental OTAs is out of scope for Custota, but if they're already generated some other way, Custota can make use of them.

The vbmeta digest of the current running system is used to select which incremental OTA to install. This is cryptographically tied to a specific OS build, so there is no chance that an incremental OTA gets applied to an incompatible OS. (Unlike eg. if the Android build fingerprint were used instead.)

### CODE REVIEW

**Comment by chenxiaolong** [comment]
@pixincreate You might be interested in this :slightly_smiling_face: (in case you want to play around with avbroot-inc-ota)

This will be included in Custota 5.4, which I plan to release in a couple hours after a couple more small changes.

**Comment by pixincreate** [comment]
oh! thanks for this! i'll try to poke around and see if i can get incremental otas to work with pixeneos...😁😅

**Comment by pixincreate** [comment]
I was looking into `avbroot-inc-ota` to generate incremental ota so that i can directly patch `my-avbroot-setup` with `sed` to do necessary modifications on the go.

Now that I think about it, I do not think generating incremental ota is feasible enough, at least, until i setup my own server (with self hosted github runner) that has got the required storage to get download the aosp source code. 

in fact, i just went ahead with adding support until i hit this blocker.  

for now, i'll continue to make necessary changes to it support this feature. but yeah, it cannot work on github ci, lol.

**Comment by chenxiaolong** [comment]
Haha, yeah, I know the feeling...
```
[20:06:45] cxl-desktop-1 …/RSAF  master [⇡] 
❯ du -chs /media/scratch/GrapheneOS 
446G    /media/scratch/GrapheneOS
446G    total
```

The dependency on AOSP's delta_generator is the main reason why avbroot-inc-ota is not integrated into avbroot. The logic for generating incremental OTAs is unfortunately far too complicated for me to reimplement too.

**Comment by pixincreate** [comment]
Ah! Yeah! I too agree with that. And from my understanding, `delta_generator` is not an independent tool at all but rather it depends completely on AOSP source code.

Do you think of any other tool similar to delta_generator that is small and does not require AOSP source code? Asking so because I did try searching for it, but unfortunately most the what I read were negative.

**Comment by chenxiaolong** [comment]
I don't think so :slightly_frowning_face: A lot of the complexity in delta_generator is because they perform a lot of tricks that are necessary to keep the size of incremental OTAs small. A simpler implementation that, for example, uses plain old bsdiff is definitely possible, but the incremental OTAs would be so huge that there's no point to use them over full OTAs.

**Comment by pixincreate** [comment]
yeah, hard agree to this! i'm better off using the existing full size ota 😅

**Pull request merged**
